services:
  python:
    container_name: python
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000    
    depends_on:
      - mysql
    restart: always
      
  mysqld:
    image: mysql
    container_name: mysqld
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - mysqld-vol:/var/lib/mysqld/data
    restart: always

volumes:
  mysqld-vol:

#   postgres-vol:

  # postgres:
  #   image: postgres
  #   container_name: postgres
  #   env_file: .env
  #   volumes:
  #     - postgres-vol:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
